version: '2'

services:
  nginx:
    image: nginx:latest
    ports: 
      - "1080:80"
      - "8443:443"
    depends_on:
      - postgres
    links:
      - postgres:db

  postgres:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=opg

